"""Explicit recovery disposition for a context-stopped loop (design review §3.2).

``AgentState.signal`` records *that* the loop stopped, not *why*.  Recovering
from a context failure needs the cause as a second channel, and the answer to
one question: does the host need to re-run the model turn, or only retry the
final archive of an answer that already exists?

``AgentRuntime`` used to keep that channel in two loose private flags written
at eleven scattered sites.  This collaborator owns the state behind named
transitions and exposes the single ``mode`` decision the runtime asks for.
"""
from __future__ import annotations

from typing import Literal

RecoveryMode = Literal["none", "archive_only", "full"]

_STORAGE_FAILED = "context_storage_failed"


class ContextRecovery:
    def __init__(self) -> None:
        self._stop_reason: str | None = None
        self._completion_pending = False

    # ── Transitions ───────────────────────────────────────────────────────────
    def stop(self, reason: str) -> None:
        """Record why the loop stopped for context (preflight or archive failure).

        Overwrites any previous reason but leaves the pending-answer disposition
        untouched: a storage failure discovered during the final archive is
        layered on top of whatever preflight reason came before it.
        """
        self._stop_reason = reason

    def note_archive_failure(self, *, answer_pending: bool) -> None:
        """Record that the post-turn archive failed.

        ``answer_pending`` is true only when the failed archive belonged to a
        completed turn, i.e. a final assistant answer already exists and must
        not be regenerated by a retry.
        """
        self._completion_pending = answer_pending

    def clear_completion(self) -> None:
        """The archive succeeded; keep any stop reason for observability."""
        self._completion_pending = False

    def clear(self) -> None:
        """Return to the fresh state (new prompt, or a successful retry)."""
        self._stop_reason = None
        self._completion_pending = False

    # ── Decisions ─────────────────────────────────────────────────────────────
    @property
    def mode(self) -> RecoveryMode:
        if self._stop_reason is None:
            return "none"
        return "archive_only" if self._completion_pending else "full"

    @property
    def stopped(self) -> bool:
        return self._stop_reason is not None

    @property
    def archive_blocked(self) -> bool:
        return self._stop_reason == _STORAGE_FAILED
